require "config.options"
require "config.keymaps"
require "config.autocmds"

LZN = require "lz.n"
LZN.load "plugins.coding"
LZN.load "plugins.debug"
LZN.load "plugins.editor"
LZN.load "plugins.git"
LZN.load "plugins.lang"
LZN.load "plugins.tools"
LZN.load "plugins.ui"